---

- hosts: localhost
  tasks: 
    - name: Download base image
      vars:
        ansible_python_interpreter: /usr/bin/python
      get_url:
        url: "{{ base_image_url }}"
        dest: /tmp/base.img

    - name: Upload image to glance
      os_image:
        name: "{{ base_image }}"
        filename: /tmp/base.img
        state: present

    - name: Check if packer image is built
      os_image_facts:
        image: "{{ benchmark_image }}"
      register: result
      changed_when: not result.ansible_facts.openstack_image
      notify: build image

  handlers:
    - name: build image
      command: packer build packer.json
      environment:
        PACKER_VAR_network: "{{ network }}"
        PACKER_VAR_floating_network: "{{ floating_network }}"
        PACKER_VAR_benchmark_image: "{{ benchmark_image }}"
        PACKER_VAR_base_image: "{{ base_image }}"
        PACKER_VAR_flavor: "{{ flavor }}"
