---

- hosts: default
  become: true
  tasks:
    - name: install dependencies
      apt:
        name:
          - build-essential
          - libatlas-base-dev
          - libopenmpi-dev
          - gfortran
          - iperf
        state: present
        update_cache: true

    - name: copy iperf service file
      copy:
        src: files/iperf.service
        dest: /etc/systemd/system/iperf.service
        mode: 0755
        owner: root

    - name: enable iperf
      service:
        name: iperf
        enabled: true

    - name: download hpl
      unarchive:
        src: http://www.netlib.org/benchmark/hpl/hpl-2.3.tar.gz
        dest: /tmp
        remote_src: yes

    - name: copy to /hpl
      synchronize:
        src: /tmp/hpl-2.3/
        dest: /hpl
      delegate_to: "{{ inventory_hostname }}"

    - name: copy makefile
      copy:
        src: files/Make.ubuntu
        dest: /hpl/
  
    - name: compile
      command: make arch=ubuntu
      args:
        creates: /hpl/bin/ubuntu/xhpl
        chdir: /hpl
