---

- hosts: compute:!benchmark-compute-0
  vars:
    output_file: iperf-{{ inventory_hostname }}-{{ ansible_date_time.iso8601_basic_short }}
    strategy: free
  tasks:
    - command: iperf -c {{ hostvars["benchmark-compute-0"].ansible_host }} -t 600 -P 8
      register: result
    - name: create results directory
      file:
        path: results
        state: directory
      delegate_to: localhost
    - name: copy
      vars:
        # (libselinux-python) aren't installed!
        ansible_python_interpreter: /usr/bin/python
      copy: content="{{ result.stdout }}" dest="results/{{ output_file }}.stdout"
      delegate_to: localhost
