ansible_ssh_extra_args: -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no
  -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -o StrictHostKeyChecking=no
  -o UserKnownHostsFile=/dev/null -W %h:%p {{ login_user }}@{{ floating_ip }}"
base_image: ubuntu-focal-18-03-2020
base_image_url: https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
flavor: m1.xlarge
floating_ip: 10.128.91.23
floating_network: external
benchmark_image: ubuntu-hpl
key: stackhpc-ansible-0
login_user: ubuntu
# tenant network UUID
network: fa2a5db9-4eac-4b30-80be-813f1ee67168
