---

- name: copy input file
  copy:
    src: files/HPL.dat
    dest: /tmp/HPL.dat

- name: run HPL
  command: mpirun -np {{ processes }} --allow-run-as-root /hpl/bin/ubuntu/xhpl
  args:
    chdir: /tmp
  register: result

- name: create results directory
  file:
    path: results
    state: directory
  delegate_to: localhost

- name: copy
  vars:
    # (libselinux-python) aren't installed!
    ansible_python_interpreter: /usr/bin/python
  copy: content="{{ result.stdout }}" dest="results/{{ instance_name }}.stdout"
  delegate_to: localhost

